import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import authRouter from './routes/auth';
import dashboardRouter from './routes/dashboard';
import customersRouter from './routes/customers';
import productsRouter from './routes/products';
import inventoryRouter from './routes/inventory';
import challansRouter from './routes/challans';
import usersRouter from './routes/users';
import auditRouter from './routes/audit';
import invoicesRouter from './routes/invoices';
import { errorHandler } from './middleware/error';
import { config } from './config';
import { pool } from './db';

export const app=express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({origin:config.corsOrigin.split(',').map(s=>s.trim())}));
app.use(express.json({limit:'1mb'}));
app.use(morgan('tiny'));
app.get('/health',(_req,res)=>res.json({status:'ok',service:'opsflow-api',timestamp:new Date().toISOString()}));
app.get('/ready',async(_req,res)=>{try { await pool.query('SELECT 1'); res.json({status:'ready'}); } catch { res.status(503).json({status:'not_ready'}); }});
app.use('/api/auth',authRouter);
app.use('/api/dashboard',dashboardRouter);
app.use('/api/customers',customersRouter);
app.use('/api/products',productsRouter);
app.use('/api/inventory',inventoryRouter);
app.use('/api/challans',challansRouter);
app.use('/api/users',usersRouter);
app.use('/api/audit',auditRouter);
app.use('/api/invoices',invoicesRouter);
app.use((_req,res)=>res.status(404).json({success:false,message:'Route not found'}));
app.use(errorHandler);
