import {useEffect,useState} from 'react';
import {Plus,Search,SlidersHorizontal,ChevronRight,Edit3} from 'lucide-react';
import {Link} from 'react-router-dom';
import {api,formatDate} from '../api'; import {Customer} from '../types';
import PageHeader from '../components/PageHeader'; import Modal from '../components/Modal'; import Badge from '../components/Badge'; import EmptyState from '../components/EmptyState'; import Loading from '../components/Loading'; import Toast from '../components/Toast';

const blank={name:'',mobile:'',email:'',businessName:'',gstNumber:'',type:'WHOLESALE',address:'',status:'LEAD',followUpDate:'',notes:''};
export default function Customers(){
 const [rows,setRows]=useState<Customer[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [type,setType]=useState(''); const [open,setOpen]=useState(false); const [form,setForm]=useState<any>(blank); const [editing,setEditing]=useState<string|null>(null); const [toast,setToast]=useState<{m:string;t:'success'|'error'}|null>(null);
 const load=()=>{setLoading(true);api.get('/customers',{params:{search,status,type,limit:50}}).then(r=>setRows(r.data.data)).finally(()=>setLoading(false));}; useEffect(load,[search,status,type]);
 const submit=async(e:any)=>{e.preventDefault();try{if(editing)await api.put(`/customers/${editing}`,form);else await api.post('/customers',form);setOpen(false);setEditing(null);setForm(blank);setToast({m:editing?'Customer updated':'Customer created',t:'success'});load();}catch(err:any){setToast({m:err?.response?.data?.message||'Could not save customer',t:'error'})}};
 const edit=(c:any)=>{setEditing(c.id);setForm({...c,businessName:c.businessName,gstNumber:c.gstNumber||'',followUpDate:c.followUpDate?.slice(0,10)||'',notes:c.notes||''});setOpen(true)};
 return <div><PageHeader eyebrow="CRM / CUSTOMERS" title="Customers" subtitle="Manage relationships, business details and the next follow-up." action={<button className="btn btn-primary" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}><Plus size={17}/> Add customer</button>}/>
 <div className="toolbar"><div className="search-box"><Search size={17}/><input placeholder="Search name, business or mobile…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filter-group"><SlidersHorizontal size={15}/><select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option><option value="RETAIL">Retail</option><option value="WHOLESALE">Wholesale</option><option value="DISTRIBUTOR">Distributor</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="LEAD">Lead</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div></div>
 <div className="panel table-panel">{loading?<Loading/>:rows.length===0?<EmptyState title="No customers found" subtitle="Try a different search or add your first customer." action={<button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={16}/> Add customer</button>}/>:<div className="table-shell"><table><thead><tr><th>Customer</th><th>Business</th><th>Type</th><th>Status</th><th>Follow-up</th><th>Contact</th><th></th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><div className="person-cell"><div className="avatar small">{c.name.slice(0,1)}</div><div><strong>{c.name}</strong><span>{c.email||'No email'}</span></div></div></td><td>{c.businessName}</td><td>{c.type}</td><td><Badge value={c.status}/></td><td>{formatDate(c.followUpDate)}</td><td>{c.mobile}</td><td><div className="row-actions"><button className="icon-btn" title="Edit" onClick={()=>edit(c)}><Edit3 size={16}/></button><Link className="icon-btn" title="View" to={`/customers/${c.id}`}><ChevronRight size={17}/></Link></div></td></tr>)}</tbody></table></div>}</div>
 <Modal open={open} title={editing?'Edit customer':'Add customer'} onClose={()=>setOpen(false)} wide><form onSubmit={submit} className="form-grid"><label>Customer name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Mobile number<input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Business name<input value={form.businessName} onChange={e=>setForm({...form,businessName:e.target.value})} required/></label><label>GST number<input value={form.gstNumber} onChange={e=>setForm({...form,gstNumber:e.target.value})}/></label><label>Customer type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="RETAIL">Retail</option><option value="WHOLESALE">Wholesale</option><option value="DISTRIBUTOR">Distributor</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="LEAD">Lead</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label>Follow-up date<input type="date" value={form.followUpDate} onChange={e=>setForm({...form,followUpDate:e.target.value})}/></label><label className="full">Address<textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})} rows={3} required/></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={3} placeholder="Context that helps the next person pick up the conversation…"/></label><div className="modal-actions full"><button className="btn btn-ghost" type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" type="submit">{editing?'Save changes':'Create customer'}</button></div></form></Modal>
 {toast&&<Toast message={toast.m} type={toast.t} onClose={()=>setToast(null)}/>}</div>
}
