import {useEffect,useMemo,useState, type CSSProperties} from 'react';
import {motion} from 'framer-motion';
import {Link} from 'react-router-dom';
import {Users,Package,TriangleAlert,FileCheck2,ArrowUpRight,CalendarClock,Activity,ChevronRight,ArrowRight,ShieldCheck} from 'lucide-react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {api,formatDate,money} from '../api';
import {useAuth} from '../auth'; import PageHeader from '../components/PageHeader'; import StatCard from '../components/StatCard'; import Badge from '../components/Badge'; import Loading from '../components/Loading';

export default function Dashboard(){
 const {user}=useAuth(); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{api.get('/dashboard/summary').then(r=>setData(r.data.data)).finally(()=>setLoading(false));},[]);
 const stockTrend=useMemo(()=>{if(!data?.stockTrend)return[]; const map=new Map<string,any>(); data.stockTrend.forEach((x:any)=>{if(!map.has(x.date))map.set(x.date,{date:x.date.slice(5),IN:0,OUT:0});map.get(x.date)[x.type]=Number(x.quantity)});return [...map.values()]},[data]);
 if(loading)return <><PageHeader eyebrow="COMMAND CENTER" title={`Good morning, ${user?.fullName?.split(' ')[0]}.`} subtitle="Your operations snapshot is loading."/><Loading rows={8}/></>;
 const k=data.kpis;
 const visibleExceptions=(data.exceptionQueue||[]).filter((e:any)=>e.href==='/' || e.href==='/challans' || (e.href==='/customers'&&['ADMIN','SALES'].includes(user?.role||'')) || (e.href==='/products'&&['ADMIN','WAREHOUSE'].includes(user?.role||'')));
 return <div className="dashboard-page"><PageHeader eyebrow="COMMAND CENTER" title={`Good morning, ${user?.fullName?.split(' ')[0]}.`} subtitle="Here's the pulse of your customers, stock and sales activity." action={<div className="status-banner"><span className="online-dot"/>All systems operational</div>}/>
 <motion.div className="signal-strip" initial={{opacity:0,y:8}} animate={{opacity:1,y:0,transition:{delay:.04}}}><div className="signal-main"><span className="signal-kicker">TODAY'S CONTROL PLANE</span><strong>{visibleExceptions.length ? `${visibleExceptions.length} operational signal${visibleExceptions.length===1?'':'s'} need attention.` : 'No exceptions are waiting for an owner.'}</strong><span>Use the radar below to move from insight to action without opening five different screens.</span></div><div className="signal-badges"><span><i className="signal-dot blue"/>Stock guarded</span><span><i className="signal-dot green"/>Audit logging</span><span><i className="signal-dot amber"/>CRM pulse</span></div></motion.div>
 <div className="stats-grid"><StatCard label="Customers" value={k.customers} meta="CRM records" icon={Users} tone="blue"/><StatCard label="Products" value={k.products} meta="Across warehouses" icon={Package} tone="violet"/><StatCard label="Low stock" value={k.lowStock} meta="Needs attention" icon={TriangleAlert} tone="amber"/><StatCard label="Confirmed challans" value={k.confirmedChallans} meta="Stock-backed orders" icon={FileCheck2} tone="green"/></div>
 <div className="dashboard-grid"><motion.div className="panel chart-panel" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><div className="panel-head"><div><h3>Stock movement pulse</h3><p>Inbound vs outbound quantities over the last 14 days.</p></div><div className="legend"><span><i className="legend-dot inbound"/>IN</span><span><i className="legend-dot outbound"/>OUT</span></div></div><div className="chart-wrap">{stockTrend.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={stockTrend}><defs><linearGradient id="inFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity="0.28"/><stop offset="100%" stopColor="#2563eb" stopOpacity="0"/></linearGradient><linearGradient id="outFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#f97316" stopOpacity="0.2"/><stop offset="100%" stopColor="#f97316" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip/><Area type="monotone" dataKey="IN" stroke="#2563eb" fill="url(#inFill)" strokeWidth={2}/><Area type="monotone" dataKey="OUT" stroke="#f97316" fill="url(#outFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<div className="empty-chart">No movement data yet.</div>}</div></motion.div>
 <motion.div className="panel attention-panel" initial={{opacity:0,y:10}} animate={{opacity:1,y:0,transition:{delay:.08}}}><div className="panel-head"><div><h3>Stock watch</h3><p>Items below their minimum threshold.</p></div><Activity size={18} className="muted-icon"/></div>{data.lowStockProducts.length===0?<div className="success-state"><FileCheck2 size={28}/><strong>Everything is healthy</strong><span>No low-stock items right now.</span></div>:<div className="mini-list">{data.lowStockProducts.map((p:any)=><div className="mini-row" key={p.id}><div><strong>{p.name}</strong><span>{p.sku} · {p.warehouse}</span></div><div className="stock-qty"><strong>{p.current_stock}</strong><small>/ {p.min_stock}</small><Badge value={p.stock_status}/></div></div>)}</div>}</motion.div></div>
 <div className="operations-grid">
 <motion.div className="panel ops-score-panel" initial={{opacity:0,y:10}} animate={{opacity:1,y:0,transition:{delay:.14}}}>
   <div className="panel-head"><div><h3>Operations readiness</h3><p>A lightweight control score for today's exception load.</p></div><ShieldCheck size={18} className="muted-icon"/></div>
   <div className="score-body"><div className="score-ring" style={{'--score': `${data.opsScore || 0}%`} as CSSProperties}><div><strong>{data.opsScore}</strong><span>/ 100</span></div></div><div className="score-copy"><strong>{data.opsScore >= 80 ? 'Clear to operate' : data.opsScore >= 55 ? 'Watch the queue' : 'Intervention needed'}</strong><span>{data.signals?.lowStock || 0} stock alerts · {data.signals?.overdueFollowups || 0} overdue follow-ups · {data.signals?.draftChallans || 0} drafts</span></div></div>
 </motion.div>
 <motion.div className="panel exception-panel" initial={{opacity:0,y:10}} animate={{opacity:1,y:0,transition:{delay:.18}}}>
   <div className="panel-head"><div><h3>Exception radar</h3><p>Five-or-fewer items worth a human look.</p></div><TriangleAlert size={18} className="muted-icon"/></div>
   <div className="exception-list">{visibleExceptions.length ? visibleExceptions.map((e:any,idx:number)=><Link className="exception-row" to={e.href} key={`${e.type}-${idx}`}><div className={`exception-priority ${e.priority.toLowerCase()}`}>{e.priority}</div><div><strong>{e.title}</strong><span>{e.detail}</span></div><ArrowRight size={15}/></Link>) : <div className="empty-small">No operational exceptions detected. Nice work.</div>}</div>
 </motion.div>
 </div>
 <div className="dashboard-grid lower"><div className="panel"><div className="panel-head"><div><h3>Recent challans</h3><p>Latest sales dispatch activity.</p></div><Link className="text-link" to="/challans">View all <ChevronRight size={15}/></Link></div><div className="table-shell"><table><thead><tr><th>Challan</th><th>Customer</th><th>Qty</th><th>Status</th><th>Date</th></tr></thead><tbody>{data.recentChallans.map((c:any)=><tr key={c.id}><td><strong>{c.challanNumber}</strong></td><td>{c.customer}</td><td>{c.totalQuantity}</td><td><Badge value={c.status}/></td><td>{formatDate(c.createdAt)}</td></tr>)}</tbody></table></div></div>
 <div className="panel"><div className="panel-head"><div><h3>Follow-up pulse</h3><p>Conversations due within 7 days.</p></div><CalendarClock size={18} className="muted-icon"/></div><div className="mini-list">{data.followups.length===0?<div className="empty-small">No follow-ups due.</div>:data.followups.map((f:any)=><div className="mini-row" key={f.id}><div><strong>{f.name}</strong><span>{f.business_name}</span></div><div className="due"><span>{formatDate(f.follow_up_date)}</span><ArrowUpRight size={15}/></div></div>)}</div></div></div>
 <div className="insight-strip"><div className="insight-icon"><Activity size={20}/></div><div><strong>OpsFlow insight</strong><span>Use the stock guard on every confirmed challan; it re-checks availability inside a database transaction before any OUT movement is written.</span></div><div className="insight-stat"><span>Reliability</span><strong>Protected</strong></div></div>
 </div>
}
