import {FormEvent,useState} from 'react';
import {motion} from 'framer-motion';
import {ArrowRight,Eye,EyeOff,ShieldCheck,Boxes,Users,BarChart3} from 'lucide-react';
import {useAuth} from '../auth';
import {useNavigate} from 'react-router-dom';

export default function Login(){
 const {login}=useAuth(); const navigate=useNavigate(); const [email,setEmail]=useState('admin@opsflow.demo'); const [password,setPassword]=useState('Demo@123'); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{await login(email,password);navigate('/')}catch(err:any){setError(err?.response?.data?.message||'Unable to sign in')}finally{setLoading(false)}};
 return <div className="login-page"><div className="login-orbit orbit-a"/><div className="login-orbit orbit-b"/><motion.section className="login-visual" initial={{opacity:0,x:-25}} animate={{opacity:1,x:0}} transition={{duration:.6}}><div className="login-brand"><div className="brand-mark large">O</div><div><strong>OpsFlow</strong><span>ERP & CRM</span></div></div><div className="hero-copy"><div className="eyebrow">OPERATIONS CONTROL PLANE</div><h1>Turn daily operations into a <span>clear next move.</span></h1><p>Customers, inventory, challans and follow-ups in one calm workspace built for fast-moving teams.</p></div><div className="visual-grid"><div className="visual-card"><BarChart3 size={18}/><div><strong>Pulse metrics</strong><span>Know what needs attention.</span></div></div><div className="visual-card"><Boxes size={18}/><div><strong>Stock guard</strong><span>Prevent negative inventory.</span></div></div><div className="visual-card"><Users size={18}/><div><strong>CRM follow-ups</strong><span>Keep every lead warm.</span></div></div></div></motion.section>
 <motion.section className="login-panel" initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} transition={{duration:.6,delay:.1}}><div className="login-card"><div className="login-head"><div className="tiny-icon"><ShieldCheck size={18}/></div><div><h2>Welcome back</h2><p>Sign in to your operations workspace.</p></div></div><form onSubmit={submit} className="form-stack"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" required/></label><label>Password<div className="password-wrap"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{error&&<div className="form-error">{error}</div>}<button className="btn btn-primary btn-lg" disabled={loading}>{loading?'Signing in…':'Sign in'}<ArrowRight size={17}/></button></form><div className="demo-box"><strong>Demo access</strong><span>Use any seeded role</span><code>admin@opsflow.demo · Demo@123</code></div></div><div className="login-footer">Secure role-based access · OpsFlow demo environment</div></motion.section></div>
}
